function m2ui64GLCM = CalculateGLCM_BinOnTheFly_IntegerMatrix(m3uiMatrix, m3bRoiMask, vi64OffsetVector, dFirstBinEdge, dBinSize, ui64NumBins)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes her

CalculateGLCM_InputValidation(m3uiMatrix, m3bRoiMask, vi64OffsetVector, dFirstBinEdge, dBinSize, ui64NumBins);

[...
    m2ui64GLCM, vi32Dims, i64Numel,...
    i64Index, i64OffsetIndex,...
    i32RowIndex, i32ColIndex, i32SliceIndex,...
    i32RowOffsetStart, i32ColOffsetStart,...
    i32RowOffsetIndex, i32ColOffsetIndex, i32SliceOffsetIndex,...
    bRowLowWatch, bRowHighWatch,...
    bColLowWatch, bColHighWatch,...
    bSliceLowWatch, bSliceHighWatch,...
    vbDimsValid] =...
    ...
    CalculateGLCM_Setup(...
    ...
    m3uiMatrix, vi64OffsetVector, ui64NumBins);

dNumBins = double(ui64NumBins);

while i64Index <= i64Numel
    
    if all(vbDimsValid) && m3bRoiMask(i64Index) && m3bRoiMask(i64OffsetIndex)
        dRow = BinImage_PerformBinCalculation(...
            double(m3uiMatrix(i64Index)),...
            dFirstBinEdge, dBinSize, dNumBins);
        
        dCol = BinImage_PerformBinCalculation(...
            double(m3uiMatrix(i64OffsetIndex)),...
            dFirstBinEdge, dBinSize, dNumBins);
        
        m2ui64GLCM(dRow, dCol) = m2ui64GLCM(dRow, dCol) + uint64(1);        
    end
    
    [...
        i64OffsetIndex, i64Index,...
        i32RowIndex, i32ColIndex, i32SliceIndex,...
        i32RowOffsetIndex, i32ColOffsetIndex, i32SliceOffsetIndex,...
        vbDimsValid] =...
        ...
        CalculateGLCM_LoopIndicesUpdate(...
        ...
        vi32Dims, i64OffsetIndex, i64Index,...
        i32RowIndex, i32ColIndex, i32SliceIndex,...
        i32RowOffsetStart, i32ColOffsetStart,...
        i32RowOffsetIndex, i32ColOffsetIndex, i32SliceOffsetIndex,...
        bRowLowWatch, bRowHighWatch,...
        bColLowWatch, bColHighWatch,...
        bSliceLowWatch, bSliceHighWatch,...
        vbDimsValid);
end















% % % % [...
% % % %     m2ui64GLCM, vi32Dims, i64Numel,...
% % % %     i64Index, i64OffsetIndex,...
% % % %     i32RowIndex, i32ColIndex, i32SliceIndex,...
% % % %     i32RowOffsetStart, i32ColOffsetStart,...
% % % %     i32RowOffsetIndex, i32ColOffsetIndex, i32SliceOffsetIndex,...
% % % %     bRowLowWatch, bRowHighWatch,...
% % % %     bColLowWatch, bColHighWatch,...
% % % %     bSliceLowWatch, bSliceHighWatch,...
% % % %     vbDimsValid] =...
% % % %     ...
% % % %     BinOnTheFly_Setup(...
% % % %     ...
% % % %     m3uiMatrix, vi64OffsetVector, ui64NumBins);
% % % % 
% % % % iMaxRow = cast(ui64NumBins, 'like', m3uiMatrix);
% % % % iOne = cast(1, 'like', m3uiMatrix);
% % % % 
% % % % 
% % % % 
% % % % while i64Index <= i64Numel
% % % %     
% % % %     if all(vbDimsValid)
% % % %         iRowValue = max(m3uiMatrix(i64Index), uiFirstBinEdge);
% % % %         iRowValue = min(iRowValue, iLastBinEdge);
% % % %         
% % % %         iRow = idivide(m3uiMatrix(i64Index) - uiFirstBinEdge + iOne, uiBinSize, 'ceil'); % only valid for integers (rounding is built into the division operation)
% % % %         iRow = min(iRow, iMaxRow);
% % % %         iRow = max(iRow, iOne);
% % % %         
% % % %         iCol = idivide(m3uiMatrix(i64OffsetIndex) - uiFirstBinEdge + iOne, uiBinSize, 'ceil'); % only valid for integers (rounding is built into the division operation)
% % % %         iCol = min(iCol, iMaxRow);
% % % %         iCol = max(iCol, iOne);
% % % %         
% % % %         m2ui64GLCM(iRow, iCol) = m2ui64GLCM(iRow, iCol) + uint64(( m3bRoiMask(i64Index) && m3bRoiMask(i64OffsetIndex) ));        
% % % %     end
% % % %     
% % % %     [...
% % % %         i64OffsetIndex, i64Index,...
% % % %         i32RowIndex, i32ColIndex, i32SliceIndex,...
% % % %         i32RowOffsetIndex, i32ColOffsetIndex, i32SliceOffsetIndex,...
% % % %         vbDimsValid] =...
% % % %         ...
% % % %         BinOnTheFly_LoopIndicesUpdate(...
% % % %         ...
% % % %         vi32Dims, i64OffsetIndex, i64Index,...
% % % %         i32RowIndex, i32ColIndex, i32SliceIndex,...
% % % %         i32RowOffsetStart, i32ColOffsetStart,...
% % % %         i32RowOffsetIndex, i32ColOffsetIndex, i32SliceOffsetIndex,...
% % % %         bRowLowWatch, bRowHighWatch,...
% % % %         bColLowWatch, bColHighWatch,...
% % % %         bSliceLowWatch, bSliceHighWatch,...
% % % %         vbDimsValid);
% % % % end


end

