function m2iGLRLM = CalculateGLRLM_BinOnTheFly_int16(m3i16Matrix, m3bRoiMask, i32OffsetVector, dFirstBinEdge, dBinSize, ui64NumBins, dEqualityTheshold, dNumberOfColumns, bTrimColumns)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes her

bForNonIntegerMatrix = false;
bBinOnTheFly = true;

m3ui32BinnedMatrix = uint32([]); % needs to still be passed in, but won't be used

m2iGLRLM = CalculateGLRLM_Algorithm(...
    m3i16Matrix, m3ui32BinnedMatrix, m3bRoiMask,...
    i32OffsetVector,...
    dFirstBinEdge, dBinSize,...
    ui64NumBins,...
    dEqualityTheshold,...
    bForNonIntegerMatrix, bBinOnTheFly,...
    dNumberOfColumns, bTrimColumns);

end

