function m2iGLCM = CalculateGLCM_BinOnTheFly_int16(m3i16Matrix, m3bRoiMask, i64OffsetVector, dFirstBinEdge, dBinSize, ui64NumBins)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes her

m2iGLCM = CalculateGLCM_BinOnTheFly_IntegerMatrix(...
    m3i16Matrix, m3bRoiMask,...
    i64OffsetVector,...
    dFirstBinEdge, dBinSize,...
    ui64NumBins);

end

