function m2iGLRLM = CalculateGLRLM_BinOnTheFly_single(m3sgMatrix, m3bRoiMask, i32OffsetVector, sgFirstBinEdge, sgBinSize, ui64NumBins, sgEqualityThreshold, dNumberOfColumns, bTrimColumns)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes her

bForNonIntegerMatrix = true;
bBinOnTheFly = true;

m3ui32BinnedMatrix = uint32([]); % needs to still be passed in, but won't be used

m2iGLRLM = CalculateGLRLM_Algorithm(...
    m3sgMatrix, m3ui32BinnedMatrix, m3bRoiMask,...
    i32OffsetVector,...
    sgFirstBinEdge, sgBinSize,...
    ui64NumBins,...
    sgEqualityThreshold,...
    bForNonIntegerMatrix, bBinOnTheFly,...
    dNumberOfColumns, bTrimColumns);

end

