function [] = S07a_ManualContourValidation()

chDatabaseRootPath = Constants.S01_root;
chRootPath = Constants.S07_root;

c1chCodeLibraries = {...
    'SRS RECIST Study',...
    'Contour Validation',...
    'Matlab DICOM Support',...
    'Matlab General Utilities'};

chGitLogFilePath = FileUtilities.makePath(chRootPath, Constants.chCodeRepositoryVersionLogFilename);

FileUtilities.addPaths(c1chCodeLibraries);
FileUtilities.logGitCommitHashForPathsAndCheckForMasterBranches(c1chCodeLibraries, chGitLogFilePath);
    
% load database
oDatabase = PatientDatabase.load(FileUtilities.makePath(chDatabaseRootPath, Constants.chDatabaseFilename));


% set-up questions
checkboxQuestions = {...
    CheckboxQuestion('Is there a necrotic core?',           false, 'f1'),...
    CheckboxQuestion('Is the necrotic core contoured?',     true,  'f2'),...
    CheckboxQuestion('Is there edema around the tumour?',   false, 'f3'),...
    CheckboxQuestion('Inaccurate contour?',                 false, 'f4'),...
    CheckboxQuestion('Inaccurate contour label?',           false, 'f5'),...
    CheckboxQuestion('Non-Sagittal Acquisition?',           false, 'f6'),...
    CheckboxQuestion('Acquisition not well aligned?',       false, 'f7'),...    
    CheckboxQuestion('General revisit required?',           false, 'f8')
    };

dropDownQuestions = {...
    DropDownQuestion('Type of Contour:',...
    {'GTV','CTV','PTV','Unsure','Other'},...
    'GTV',...
    'numpad4'),...
    DropDownQuestion('Contour Label Interpretation:',...
    {'GTV','CTV','PTV','Other'},...
    'GTV',...
    'numpad5')};

notesDefault = {'CONTOUR NOTES: ', '', 'NECROTIC CORE NOTES: ', '', 'OTHER: ', ''};

% make contour validation patients

c1oContourValidationPatients = oDatabase.createContourValidationPatients();

dNumPatients = length(c1oContourValidationPatients);

for dPatientIndex = 1:dNumPatients
    h = ContourValidation(...
        c1oContourValidationPatients{dPatientIndex},...
        checkboxQuestions, dropDownQuestions, notesDefault);
    waitfor(h);
    
    % apply results
    oDatabase.applyContourValidationResult(c1oContourValidationPatients{dPatientIndex});
    
    oDatabase.save(FileUtilities.makePath(chRootPath, Constants.chDatabaseFilename));
    
    disp(['Patient ', num2str(dPatientIndex), '/', num2str(dNumPatients), ' Complete']);
end

end

