function m2ui64GLRLM = CalculateGLRLM_BinningPreComputed_single(m3sgRawMatrix, m3ui32BinnedMatrix, m3bRoiMask, i32OffsetVector, sgFirstBinEdge, sgBinSize, ui64NumBins, sgEqualityTheshold, dNumberOfColumns, bTrimColumns)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes her

bForNonIntegerMatrix = true;
bBinOnTheFly = false;

m2ui64GLRLM = CalculateGLRLM_Algorithm(...
    m3sgRawMatrix, m3ui32BinnedMatrix, m3bRoiMask,...
    i32OffsetVector,...
    sgFirstBinEdge, sgBinSize,...
    ui64NumBins,...
    sgEqualityTheshold,...
    bForNonIntegerMatrix, bBinOnTheFly,...
    dNumberOfColumns, bTrimColumns);

end

