function m2iGLCM = CalculateGLCM_BinOnTheFly_uint32(m3ui32Matrix, m3bRoiMask, i64OffsetVector, dFirstBinEdge, dBinSize, ui16NumBins)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes her

m2iGLCM = CalculateGLCM_BinOnTheFly_IntegerMatrix(...
    m3ui32Matrix, m3bRoiMask,...
    i64OffsetVector,...
    dFirstBinEdge, dBinSize,...
    ui16NumBins);

end

